from googleapiclient.discovery import build
import pprint
import os
import csv
import time

ingredients = [
 'corn syrup',
 'sugar',
 'peanut butter',
 'dextrose',
 'hydrogenated vegetable oil',
 'soy lecithin',
 'salt',
 'mono',
 'diglycerides',
 'maltodextrin',
 'modified food starch',
 'partially hydrogenated soybean oil',
 'citric acid',
 'artificial flavors',
 'blue 1',
 'red 40',
 'yellow 5',
 'yellow 6',
 'palm kernel  palm oil',
 'cocoa',
 'nonfat milk',
 'lactose',
 'milk protein concentrate',
 'natural  artificial flavors',
 'peppermint oil',
 'yellow 5 lake',
 'blue 1 lake',
 'artificial flavor',
 'carnauba wax',
 'acacia',
 'titanium dioxide',
 'red 40 lake',
 'gum base',
 'glucose syrup',
 'natural & artificial flavors',
 'glycerine',
 'bht',
 'peanuts',
 'honey',
 'dried egg whites',
 'coconut oil',
 'hydrogenated coconut oil',
 'almonds',
 'egg whites',
 'canola /or safflower /or palm oil',
 'modified soy protein',
 'natural flavor',
 'tbhq  citric acid',
 'sweetened condensed skim milk',
 'high fructose corn syrup',
 'partially hydrogenated coconut oil',
 'chocolate liquor',
 'whey powder',
 'calcium caseinate',
 'distilled monoglycerides',
 'artificial licorice flavor',
 'glycerin',
 'artificial coloring',
 'fd&c blue 2',
 'fd&c red 40',
 'fd&c yellow 6',
 'starch',
 'artificial colors',
 'turmeric coloring',
 'sucrose',
 'gum acacia',
 "confectioner's glaze",
 'yellow 6  blue 2',
 'calcium stearate',
 'malic acid',
 'phosphoric acid',
 'caramel color',
 'blue 2 lake',
 'yellow 6 lake',
 'glycerol',
 'acesulfame k',
 'aspartame',
 'milk chocolate',
 'palm oil',
 'sodium carbonate',
 'gelatin',
 'food coloring',
 'corn starch',
 'tapioca',
 'beef gelatin',
 'sesame oil',
 'red 3',
 'magnesium stearate',
 'blue 1  2',
 'red40',
 'nonfat dry milk',
 'egg albumen',
 'soy protein',
 'sodium citrate',
 'whole oat flour',
 'modified corn starch',
 'calcium carbonate',
 'color added',
 'trisodium phosphate',
 'zinc  iron',
 'vitamin c',
 'a b vitamin',
 'vitamin b6',
 'vitamin b2',
 'vitamin b1',
 'vitamin a',
 'vitamin b12',
 'vitamin d',
 'wheat starch',
 'vitamin e',
 'toasted coconut-contains sodium metabisulfite-a preservative',
 'sodium bicarbonate',
 'color includes yellow 5',
 'nonfat dry milk powder',
 'artificial  natural flavoring',
 'corn oil',
 'celilla wax',
 'blue 2',
 'cornstarch',
 'modifed food starch',
 'natural  artificial flavor',
 'beeswax',
 'artificial red 40',
 'pectin',
 'includes yellow 6',
 'wheat flour',
 'modified whey',
 'skim milk',
 'cream',
 'mono & diglycerides',
 'tapioca dextrin',
 'food starch-modified',
 'includes red 40',
 'yellow 5 lake yellow 6',
 'molasses',
 'licorice extract',
 'modified cornstarch',
 'k-carmine  red 40',
 'resinous glaze',
 'anise oil',
 'sulfur dioxide',
 'dry roasted peanuts',
 'hydrogenated cottonseed',
 'rapeseed oil  salt',
 'cocoa butter',
 'fractionated palm kernel oil',
 'whole milk powder',
 'non fat dry milk',
 'peanut flour',
 'soy protein isolate',
 'almond flour',
 'pecans',
 'walnuts',
 'cashews',
 'hazelnuts',
 'white grape juice from concentrate',
 'sorbitol',
 'partially hydrogenated cottonseed oil',
 'cottonseed oil',
 'monoglycerides',
 'ascorbic acid',
 'potassium citrate',
 'agar-agar',
 'xanthan gum',
 'milk',
 'chocolate',
 'milk fat',
 'soy lecithin  ppgr',
 'vanillin',
 'pear juice from concentrate',
 'fumaric acid',
 'confectioners glaze',
 'white mineral oil',
 'artificial color',
 'magnesium hydroxide',
 'red no 3',
 'red no',
 'natural & artificial flavor',
 'artificial color red 40',
 'chocolate processed with alkali',
 'invertase',
 'hydrogenated cottonseed oil',
 'natural flvors',
 'lemon juice concentrate',
 'natural flavors',
 'cocoa mass',
 'skimmed milk powder',
 'palm fat',
 'shea fat',
 'e100',
 'carmine',
 'e132',
 'e133',
 'e150a',
 'e150c',
 'e150d',
 'e153',
 'e160a',
 'e160e',
 'e162',
 'e163',
 'e171',
 'e172',
 'dextrin',
 'emulsifiers',
 'soya lecithin',
 'e445',
 'humectant sorbitol syrup',
 'coloring black carrot concentrate',
 'caramel sugar syrup',
 'polyoxyethylene sorbitan monostearate',
 'turmeric extract',
 'alpha-tocopherol',
 'pgpr',
 'emulsifier',
 'tbhq',
 'hydrogenated palm kernel oil',
 'cocoa powder process with alkali',
 'peanut',
 'caramel',
 'peanut butter in a milk chocolate coating',
 'milkfat',
 'glucose-fructose syrup',
 'humectant',
 'high maltose corn syrup',
 'palm kernel oil',
 'whey',
 'whey protein concentrate',
 'artificial flavour',
 'sodium caseinate',
 'preservative',
 'statement cocoa butter',
 'ingredients: peanuts',
 'non fat',
 'carrageenan',
 'mono  diglycerides',
 'chocolate non fat milk',
 'palm shea',
 'sunflower /or safflower oil',
 'chocolate nonfat milk',
 'cocoa processed with alkali',
 'egg white',
 'hydrolyzed milk protein',
 'invert sugar syrup',
 'soy lecithins',
 'milk powder',
 'natural vanilla  artificial flavors',
 'cashew nuts',
 'palm kernel oil  coconut oil',
 'cocoa powder',
 'nonfat milk powder',
 'soy lecithin as an emulsifier',
 'unsweetened chocolate',
 'milk ingredients',
 'chopped almonds',
 'milk  soy',
 'lecithin',
 'invert sugar',
 'whole milk',
 'butter',
 'coconut',
 'palm',
 'soybean',
 'cottonseed',
 'palm kernel)',
 'artificial & natural flavor',
 'artificial flavor contains peanuts',
 'egg  soy',
 'partially skimmed milk powder',
 'vanilla',
 'coffee beans',
 'partially defatted peanuts',
 'soybean oil',
 'corn syrup solids',
 'pretzels',
 'enriched wheat flour',
 'flour',
 'niacin',
 'ferrous sulfate',
 'thiamin mononitrate',
 'riboflavin',
 'folic acid',
 'vegetable oil',
 'canola oil',
 'yeast',
 'ammonium bicarbonate',
 'baking soda',
 'dairy butter',
 'disodium phosphate',
 'organic cacao beans',
 'organic cane sugar',
 'organic evaporated cane juice',
 'sea salt',
 'organic caramel color',
 'organic almonds',
 'organic cocoa butter',
 'organic vanilla beans',
 'natural vanilla flavor',
 'almonds roasted almonds',
 'hydrogenated',
 'rice flour',
 'corn flour',
 'palm kernel',
 'soy pieces\npeanuts',
 'malted milk',
 'barley malt extract',
 '/or sunflower oilsalt',
 'sorbitan tristearate',
 'hydrolyzed soy protein',
 'mono-  diglycerides',
 'maltitol',
 'phenylketonurics',
 'artificial  natural flavors',
 'potassium tripolyphosphate',
 'potassium chloride',
 'acesulfame potassium',
 'orange  fruit punch',
 'fd&c red 40 lake',
 'double raspberry',
 'strawberry/watermelon fd&c red 40 lake',
 'pgpr emulsifier',
 'vanillin artificial flavor',
 'xylitol',
 'natural  artificial flavoring',
 'mannitol',
 'calcium casein peptone-calcium phosphate',
 'dried whole milk',
 'cocoa vegetable oil',
 'emulsifiers (sunflower lecithin',
 'polyglycerol polyricinoleate) butterfat',
 'lactosesunflower lecithin',
 'polyglycerol polyricinoleate',
 'butterfat',
 'refined palm kernel oil',
 'pgp',
 'hydrogenated palm kernel oil /or palm oil',
 'cocoa powder processed with alkali',
 'malted barley',
 'partially hydrogenated palm kernel oil',
 'coloring',
 'emulsifier soy lecithin',
 'barley malt',
 'vanillan',
 'rice flour barley malt',
 'skim milk powder',
 'anhydrous milk fat',
 'soy',
 'sunflower lecithin',
 'modified palm oil',
 'hazelnut paste',
 'mono carrageenan',
 'mineral oil',
 'soy lecithin  vanillin',
 'brown sugar',
 'wheat glucose syrup',
 'rice starch',
 'gum arabic',
 'sucrose esters of fatty acids',
 'gellan gum',
 'fructose',
 'peppermint essential oil',
 'magnesium salts of fatty acids',
 'gelatine',
 'safflower',
 'spirulina',
 'apple',
 'elderberry',
 'blackcurrant',
 'orange',
 'kiwi',
 'lemon',
 'mango',
 'passion fruit',
 'aronia',
 'grape',
 'elderberry extract']


def google_search(search_term, **kwargs):

    api_key = ''
    cse_id = ''
    count = 10
    service = build("customsearch", "v1", developerKey=api_key)
    items =[]
    for i in range(2):
        time.sleep(1)
        start_index = count * i + 1
        res = service.cse().list(
            q=search_term, 
            cx=cse_id, num=count, lr='lang_en', 
            start=start_index).execute()
        items += res['items']
    return items

def search_ind(ind):
    search_phrase = 'is ' + ind + ' good for you?' 
    items = google_search(search_phrase)
    results = []
    
    for idx, item in enumerate(items):
        pagemap = item.get('pagemap')
        if not pagemap:
            continue

        meta = pagemap.get('metatags')
        if meta and len(meta) > 0:
            title = meta[0].get('og:title')
            description = meta[0].get('og:description')
            site_name = meta[0].get('og:site_name')
            url = meta[0].get('og:url')

            if not title or not description:
                continue

            results.append(
                {   
                    'ingredient': ind,
                    'search_phrase': search_phrase,
                    'site_name': site_name,
                    'url': url,
                    'title': title,
                    'description': description
                }
            )
    
    return results


if __name__ == '__main__':
    here = os.getcwd()
    total = len(ingredients)
    counter = 1

    # file to save the results
    ind_file_name = os.path.join(here, '01_all_ingredients.csv')

    if os.path.exists(ind_file_name):
        mode = 'a'
        print('file exists. Appending results...')
    else:
        mode = 'w'
        print('creating file')

    with open(ind_file_name, mode=mode, encoding='utf8') as csv_file:
        fieldnames = ['ingredient', 'search_phrase', 'site_name', 'url', 'title', 'description']
        writer = csv.DictWriter(csv_file, fieldnames=fieldnames)
        writer.writeheader()

        for ingredient in ingredients:
            print('{} of {}'.format(counter, total))
            print('performing search on: {}'.format(ingredient))
        
            # perform google search
            results = search_ind(ingredient)

            print('done...write results...')
            # write results
        
            for row in results:
                writer.writerow(row)
                # writer.writerow({
                #     k:v.encode('utf-8') for k,v in row.items() if v
                # })

            counter += 1

            
